spring:
  datasource:
    url: jdbc:h2:./target/local_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8888
bot:
  token: 1741756202:AAEXvS0OCon5jQAb_zO85rHrE_q0ZSz2S-0
  username: YoData
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      email: admin@admin.ru
    job-execution:
      enabled: true